# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alyosha/work/git/mtgdeckconstructor/src/MTG_GUI/new_deck.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDeck(object):
    def setupUi(self, NewDeck):
        NewDeck.setObjectName("NewDeck")
        NewDeck.resize(411, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewDeck)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.newDeckTypeLabel = QtWidgets.QLabel(NewDeck)
        self.newDeckTypeLabel.setObjectName("newDeckTypeLabel")
        self.gridLayout.addWidget(self.newDeckTypeLabel, 2, 0, 1, 1)
        self.newDeckNameLineEdit = QtWidgets.QLineEdit(NewDeck)
        self.newDeckNameLineEdit.setObjectName("newDeckNameLineEdit")
        self.gridLayout.addWidget(self.newDeckNameLineEdit, 0, 1, 1, 1)
        self.newDeckTypeComboBox = QtWidgets.QComboBox(NewDeck)
        self.newDeckTypeComboBox.setObjectName("newDeckTypeComboBox")
        self.newDeckTypeComboBox.addItem("")
        self.newDeckTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.newDeckTypeComboBox, 2, 1, 1, 1)
        self.newDeckNameLabel = QtWidgets.QLabel(NewDeck)
        self.newDeckNameLabel.setObjectName("newDeckNameLabel")
        self.gridLayout.addWidget(self.newDeckNameLabel, 0, 0, 1, 1)
        self.newDeckDuplicatePushButton = QtWidgets.QPushButton(NewDeck)
        self.newDeckDuplicatePushButton.setObjectName("newDeckDuplicatePushButton")
        self.gridLayout.addWidget(self.newDeckDuplicatePushButton, 1, 0, 1, 1)
        self.newDeckDuplicateLineEdit = QtWidgets.QLineEdit(NewDeck)
        self.newDeckDuplicateLineEdit.setEnabled(False)
        self.newDeckDuplicateLineEdit.setObjectName("newDeckDuplicateLineEdit")
        self.gridLayout.addWidget(self.newDeckDuplicateLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.newDeckOkPushButton = QtWidgets.QPushButton(NewDeck)
        self.newDeckOkPushButton.setObjectName("newDeckOkPushButton")
        self.horizontalLayout.addWidget(self.newDeckOkPushButton)
        self.newDeckCancelPushButton = QtWidgets.QPushButton(NewDeck)
        self.newDeckCancelPushButton.setObjectName("newDeckCancelPushButton")
        self.horizontalLayout.addWidget(self.newDeckCancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NewDeck)
        QtCore.QMetaObject.connectSlotsByName(NewDeck)

    def retranslateUi(self, NewDeck):
        _translate = QtCore.QCoreApplication.translate
        NewDeck.setWindowTitle(_translate("NewDeck", "Create New Deck"))
        self.newDeckTypeLabel.setText(_translate("NewDeck", "Deck Type"))
        self.newDeckTypeComboBox.setItemText(0, _translate("NewDeck", "Standard"))
        self.newDeckTypeComboBox.setItemText(1, _translate("NewDeck", "Commander"))
        self.newDeckNameLabel.setText(_translate("NewDeck", "Deck Name"))
        self.newDeckDuplicatePushButton.setText(_translate("NewDeck", "Duplicate..."))
        self.newDeckOkPushButton.setText(_translate("NewDeck", "Ok"))
        self.newDeckCancelPushButton.setText(_translate("NewDeck", "Cancel"))
